package cz.zcu.fav.pia.ioc.web;

import java.util.List;

import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import cz.zcu.fav.pia.ioc.service.IocService;
import lombok.RequiredArgsConstructor;

@RestController // Marks this bean as a REST Controller - Spring loads it and configures it appropriately
@RequiredArgsConstructor // Lombok annotation creating a constructor with all the private final fields
public class IocController {

	/*
	 * You see we have a private final field here, but do not set its value. It is
	 * done in the constructor generated by Lombok (see @RequiredArgsConstructor above).
	 * The constructor is automatically called by Spring when creating this bean. This is
	 * a Dependency Injection through a constructor.
	 *
	 * Notice the use of the IocService interface, Spring tries to find an implementation
	 * for you.
	 */
	private final IocService service;

	/*
	 * This method is mapped to the / URI and Spring automatically converts the data provided to a JSON.
	 * See http://localhost:8080/.
	 */
	@RequestMapping("/")
	public List<String> names() {
		return service.getNames();
	}

}
